# Generated by Django 4.2.9 on 2024-01-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='acc_status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='appuser',
            old_name='superuser',
            new_name='is_superuser',
        ),
    ]
